user = input(" What is your name? ")
if user == "Tioluwani":
    print("Oh its you the drama queen,How did you gain access to Karo's laptop")
    print("Karo has told me alot about you.")
    print("Like how you annoy him alot and just won't live Akindele alone")
    input(" WHAT IS 1+1? ")
    print("Incorrect the answer is 10 because 1+1 in binary is 10,")
    print("How did you miss such a simple question")
    print("Oh,I know why people result to being dramatic sometimes as a result of neglect or neurodevelopmental issues")
    print("Goodbye and Good riddance")
elif user == "Karo":
    print("Hey " + user)
    print("Long time no see,")
    input("How are you doing? ")
    print("Do you want to hear a joke")
    input()
    print("What do you call a deer that has no eyes?")
    input()
    print("I have no i-dea")
    print("It was nice being wth you again")
    print("GOODBYE")
    input()
elif user == "Zion":
    print("Hello Zion,My name is Bixby an interactive interface created by Karo")
    print("Would you like hear a joke")
    input()
    print("What does a chicken drum with? ")
    input()
    print("CHICKEN DRUMSTICKS")
    print("Oh sorry i got to go")
    print("It was nice meeting you,GOODBYE ")
elif user == "Toluwani":
    print("Hello Tolu, Karo your friend has told me a lot about you and your interest towards coding")
    print("Would you like hear a joke")
    input()
    print("What does a chicken drum with? ")
    input()
    print("CHICKEN DRUMSTICKS")
    print("Oh sorry i got to go")
    print("It was nice meeting you,GOODBYE ")
elif user == "Temioluwa":
    print("Well,Well,Well look who I have here")
    print("Akindele the wannabe video editor")
    input()
    print("Karo has told me alot about you ")
    input()
    print("Anyways it was nice meeting you")
    print("GOODBYE ")
elif user == "Guest":
    print("Hello newbie,My name is Bixby an interactive interface created by Karo")
    print("Will you like hear a joke")
    input()
    print("What does a chicken drum with? ")
    input()
    print("CHICKEN DRUMSTICKS")
    print("Oh sorry i got to go")
    print("It was nice meeting you,GOODBYE ")
elif user == "Ayomide":
    print("Waka Jam you")
    print("Abeg shift and get out don't touch my keyboard")
elif user == "Maro":
    print("Hello" + user)
    print("Wait aren't you Karo's brother,")
    print("Wow, nice to meet you Karo has told me so much about you")
    input()
    print("I am sorry I can't hang now got to go,Goodbye")
elif user == "Babatunde":
    print("Hello Mr Baba T, nice to meet you")
    input()
    print("How are you doing")
    input()
    print("Glad to dee that I have to go bye")
elif user == "Joanna":
    print("Btw Karo is Taller than U")
else :
    print("Im afraid ur not registered in my data base")
        
    